### ISSUE TITLE
panic in bpfman-agent when trying to load XDP program

### ISSUE THREAD

**Issue by Billy99** [bpfman/bpfman-operator#328]
Author of [bpfman-Issue#1311](https://github.com/bpfman/bpfman/issues/1311) is trying to load an XDP program on OpenShift for the first time and has had several issues. Based on the logs (full logs attached below), bpfman-agent has a panic. Here is a snippet:

```
{"level":"error","ts":"2024-10-21T06:04:09Z","msg":"Observed a panic","controller":"xdpprogram","controllerGroup":"bpfman.io","controllerKind":"XdpProgram","XdpProgram":{"name":"xdp-test"},"namespace":"","name":"xdp-test","reconcileID":"25b461d5-bf81-4695-8c3f-dfe3af75fa23","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"goroutine 369 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x220c558, 0xc0012dedb0}, {0x1c26360, 0x3244500})\n\t/usr/src/bpfman-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:105 +0x112\npanic({0x1c26360?, 0x3244500?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).handleProgCreateOrUpdate(0xc0001c2900, {0x220c558, 0xc0012dedb0}, {0x221e590, 0xc0001c2900}, 0xc00126c6f0, 0xc0011f3500, 0xc0012df440, 0x1, 0x0, ...)\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:796 +0x9f1\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileProgram(0xc0001c2900, {0x220c558, 0xc0012dedb0}, {0x221e590, 0xc0001c2900}, {0x2233f78?, 0xc0013c0008?}, 0xc0012df440)\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:876 +0x5ad\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon(0xc0001c2900, {0x220c558, 0xc0012dedb0}, {0x221e590, 0xc0001c2900}, {0xc000fc0de0, 0x2, 0x0?})\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:167 +0x30b\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*XdpProgramReconciler).Reconcile(0xc0001c2900, {0x220c558, 0xc0012dedb0}, {{{0x0, 0x0}, {0xc0007a21e8, 0x8}}})\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/xdp-program.go:213 +0x592\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc0012ded20?, {0x220c558?, 0xc0012dedb0?}, {{{0x0?, 0x0?}, {0xc0007a21e8?, 0x0?}}})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116 +0xd4\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2224aa0, {0x220c590, 0xc0003274a0}, {{{0x0, 0x0}, {0xc0007a21e8, 0x8}}})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303 +0x3bc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2224aa0, {0x220c590, 0xc0003274a0})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263 +0x21d\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224 +0x8a\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 28\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:220 +0x490\n","stacktrace":"runtime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:881\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).handleProgCreateOrUpdate\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:796\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileProgram\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:876\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:167\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*XdpProgramReconciler).Reconcile\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/xdp-program.go:213\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224"}
```

Full Logs:
[7gk88-bpfman-agent.log](https://github.com/user-attachments/files/17482074/7gk88-bpfman-agent.log)
[7gk88-bpfman.log](https://github.com/user-attachments/files/17482075/7gk88-bpfman.log)

**Comment by Billy99** [comment]
Pulling out some of the fluff in the logs, this is what I am seeing:

**PASS 1:**
Call to bpfman to load fails with `rpc error: code = Canceled desc = stream terminated by RST_STREAM with error code: CANCEL`:
```
{"level":"info","ts":"2024-10-21T06:02:35Z","msg":"Reconcile XDP: Enter","controller":"xdpprogram","controllerGroup":"bpfman.io","controllerKind":"XdpProgram","XdpProgram":{"name":"go-xdp-counter-example"},"namespace":"","name":"go-xdp-counter-example","reconcileID":"f8b344f1-a182-48f7-92b0-ea1aaaea2bc7","ReconcileKey":{"name":"go-xdp-counter-example"}}
{"level":"info","ts":"2024-10-21T06:02:35Z","logger":"xdp","msg":"Calling bpfman to load program on node","bpfProgram name":"go-xdp-counter-example-b7aee2fc"}
{"level":"error","ts":"2024-10-21T06:03:27Z","logger":"xdp","msg":"Failed to load Program","error":"failed to load bpfProgram via bpfman: rpc error: code = Canceled desc = stream terminated by RST_STREAM with error code: CANCEL","stacktrace":"github.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileBpfProgram\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:268\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).handleProgCreateOrUpdate\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:759\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileProgram\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:876\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:167\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*XdpProgramReconciler).Reconcile\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/xdp-program.go:213\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224"}
```
If you correlate that with the bpfman log, there was a Cosign hiccup and bpfman panic'd (the panic was removed and replace with an error return in [bpfman:PR#1326](https://github.com/bpfman/bpfman/pull/1326) so bpfman should not panic here now, still an error though):
```
[INFO  bpfman::oci_utils::cosign] Starting Cosign Verifier, downloading data from Sigstore TUF repository
thread 'tokio-runtime-worker' panicked at /home/runner/work/bpfman/bpfman/bpfman/src/lib.rs:663:10:
failed to initialize image manager: Error spawning blocking task to build sigstore repo inside of tokio: Failed to fetch https://tuf-repo-cdn.sigstore.dev/6.root.json: Transport 'other' error fetching 'https://tuf-repo-cdn.sigstore.dev/6.root.json': error sending request for url (https://tuf-repo-cdn.sigstore.dev/6.root.json): error trying to connect: operation timed out
```

bpfman-agent should have dropped out here, but it keeps going and then tries to update:
```
{"level":"info","ts":"2024-10-21T06:03:27Z","logger":"xdp","msg":"Updating bpfProgram Object","Id":null,"bpfProgram":"go-xdp-counter-example-b7aee2fc"}
{"level":"error","ts":"2024-10-21T06:03:27Z","msg":"Observed a panic","controller":"xdpprogram","controllerGroup":"bpfman.io","controllerKind":"XdpProgram","XdpProgram":{"name":"go-xdp-counter-example"},"namespace":"","name":"go-xdp-counter-example","reconcileID":"f8b344f1-a182-48f7-92b0-ea1aaaea2bc7","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"goroutine 369 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x220c558, 0xc00168ee70}, {0x1c26360, 0x3244500})\n\t/usr/src/bpfman-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:105 +0x112\npanic({0x1c26360?, 0x3244500?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).handleProgCreateOrUpdate(0xc0001c2900, {0x220c558, 0xc00168ee70}, {0x221e590, 0xc0001c2900}, 0xc000d82cc0, 0xc0016a0cb0, 0xc00168f290, 0x1, 0x0, ...)\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:796 +0x9f1\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileProgram(0xc0001c2900, {0x220c558, 0xc00168ee70}, {0x221e590, 0xc0001c2900}, {0x2233f78?, 0xc001555508?}, 0xc00168f290)\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:876 +0x5ad\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon(0xc0001c2900, {0x220c558, 0xc00168ee70}, {0x221e590, 0xc0001c2900}, {0xc0016aca80, 0x2, 0x0?})\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:167 +0x30b\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*XdpProgramReconciler).Reconcile(0xc0001c2900, {0x220c558, 0xc00168ee70}, {{{0x0, 0x0}, {0xc0004b24f8, 0x16}}})\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/xdp-program.go:213 +0x592\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc00168ede0?, {0x220c558?, 0xc00168ee70?}, {{{0x0?, 0x0?}, {0xc0004b24f8?, 0x0?}}})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116 +0xd4\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2224aa0, {0x220c590, 0xc0003274a0}, {{{0x0, 0x0}, {0xc0004b24f8, 0x16}}})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303 +0x3bc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2224aa0, {0x220c590, 0xc0003274a0})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263 +0x21d\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224 +0x8a\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 28\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:220 +0x490\n","stacktrace":"runtime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:881\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).handleProgCreateOrUpdate\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:796\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileProgram\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:876\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:167\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*XdpProgramReconciler).Reconcile\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/xdp-program.go:213\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2024-10-21T06:03:27Z","msg":"Reconciler error","controller":"xdpprogram","controllerGroup":"bpfman.io","controllerKind":"XdpProgram","XdpProgram":{"name":"go-xdp-counter-example"},"namespace":"","name":"go-xdp-counter-example","reconcileID":"f8b344f1-a182-48f7-92b0-ea1aaaea2bc7","error":"panic: runtime error: invalid memory address or nil pointer dereference [recovered]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224"}
```
I see in the code where after the bpfman call fails, the code returns a NotLoaded condition code, but no error (`return bpfmaniov1alpha1.BpfProgCondNotUnloaded, nil`) so the calling code keeps processing instead of bailing. This is a bug and will be fixed in an associated PR by returning an error.

The code then checks if the KernelID matches, and if not, try to update K8s (`if !reflect.DeepEqual(existingId, r.progId) {`). I'm not able to reproduce this part, both mine must be empty. But in the logs, they are not equal so the code continues and `existingId` is nil and it is de-referenced and a panic. This is a bug as well. The function to set `existingId` (`existingId, err := bpfmanagentinternal.GetID(&existingBpfProgram)`) checks for an error after this call, but for some reason, `GetID()` is not returning an err, so an asociated PR will add an error.

**PASS 2-...:**
Call to bpfman to load fails with `rpc error: code = Aborted desc = bpf_obj_get failed`:
```
{"level":"info","ts":"2024-10-21T06:03:27Z","msg":"Reconcile XDP: Enter","controller":"xdpprogram","controllerGroup":"bpfman.io","controllerKind":"XdpProgram","XdpProgram":{quay.io/bpfman-bytecode/go-xdp-counter:latest},"namespace":"","name":"xdp-test","reconcileID":"5c10cfee-9985-4d3f-9c8e-8af929fb1f83","ReconcileKey":{"name":"xdp-test"}}
{"level":"info","ts":"2024-10-21T06:03:27Z","logger":"xdp","msg":"Calling bpfman to load program on node","bpfProgram name":"go-xdp-counter-example-b7aee2fc"}
{"level":"error","ts":"2024-10-21T06:03:55Z","logger":"xdp","msg":"Failed to load Program","error":"failed to load bpfProgram via bpfman: rpc error: code = Aborted desc = `bpf_obj_get` failed","stacktrace":"github.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileBpfProgram\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:268\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).handleProgCreateOrUpdate\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:759\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileProgram\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:876\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:167\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*XdpProgramReconciler).Reconcile\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/xdp-program.go:213\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224"}
```

Based on the bpfman logs, I just see `quay.io/bpfman-bytecode/go-xdp-counter:latest` being loaded multiple times (This is repeated in the rest of the bpfman logs):
```
[INFO  bpfman::oci_utils::cosign] Starting Cosign Verifier, downloading data from Sigstore TUF repository
[INFO  bpfman::oci_utils::cosign] The bytecode image: quay.io/bpfman-bytecode/go-xdp-counter:latest is signed
[INFO  bpfman::types] Loading program bytecode from container image: quay.io/bpfman-bytecode/go-xdp-counter:latest
[INFO  bpfman::oci_utils::cosign] The bytecode image: quay.io/bpfman/xdp-dispatcher:v0.5.4 is signed
```

But based on the bpfman-agent logs, looks like `"name":"xdp-test"` is trying to be loaded, which I'm guessing is the author's private image they are trying to load (which they indicated may have issues). The logs continue with the same `runtime error: invalid memory address or nil pointer dereference` mentioned above, and this pattern just repeats.

**Summary:**
* Two spots in bpfman-agent, an error is encountered but no error was returned. Associated PR will fix that.
* bpfman panic instead of returning error is already fixed, but can't do much about the Cosign hiccup.
* Need to add additional logs to bpfman to indicate load failures.
* Need a better way to bubble up load failures to k8s user.
